version: "3.3"

services:
  frontend:
    links:
      - backend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    restart: always    
    ports:
      - "10000:80"
    networks:
      - application-net

  backend:
    links:
      - mysqldb
    build: .
    container_name: backend
    restart: always
    ports:
      - "9000:8080"
    networks:
      - application-net
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/test?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "yash",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.sql.init.mode": "always"
      }'
            
  mysqldb:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    ports:
      - "3307:3306"
    networks:
      - application-net
    environment:
      - MYSQL_ROOT_PASSWORD=yash
      - MYSQL_DATABASE=test
       
      
networks:
  application-net:
    driver: bridge
